language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - PHP_CURRENT='5.6'

before_script:
  - composer selfupdate
  - travis_retry composer install --dev --prefer-source
  - travis_retry git clone https://github.com/padraic/humbug.git
  - cd humbug && composer install && cd ..

script:
  - make phpunit
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then php humbug/bin/humbug; fi
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then make phpcs bugfree; fi

after_script:
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then make test-upload; fi
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then curl -isb -X POST --form "filedata=@humbuglog.json;filename=report.json" http://mutator.io/report/$TRAVIS_REPO_SLUG/$TRAVIS_COMMIT/; fi

matrix:
  fast_finish: true
